# Generated by Django 6.0.5 on 2026-06-13 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('linkedin_url', models.URLField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(max_length=120)),
                ('current_role', models.CharField(blank=True, max_length=160)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('faculty', models.CharField(blank=True, choices=[('SOC', 'School of Computing'), ('ENG', 'Faculty of Engineering'), ('BIZ', 'NUS Business School'), ('FASS', 'Faculty of Arts and Social Sciences'), ('SCI', 'Faculty of Science'), ('MED', 'Yong Loo Lin School of Medicine'), ('LAW', 'Faculty of Law')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Alumni',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(blank=True, choices=[('SOC', 'School of Computing'), ('ENG', 'Faculty of Engineering'), ('BIZ', 'NUS Business School'), ('FASS', 'Faculty of Arts and Social Sciences'), ('SCI', 'Faculty of Science'), ('MED', 'Yong Loo Lin School of Medicine'), ('LAW', 'Faculty of Law')], max_length=10)),
                ('major', models.CharField(blank=True, max_length=120)),
                ('year_of_study', models.CharField(blank=True, choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('5', 'Year 5'), ('6', 'Year 6')], max_length=2)),
                ('gpa_range', models.CharField(blank=True, choices=[('0.0-2.0', '0.0-2.0'), ('2.0-3.0', '2.0-3.0'), ('3.0-3.5', '3.0-3.5'), ('3.5-4.0', '3.5-4.0'), ('4.0-5.0', '4.0-5.0')], max_length=10)),
                ('experiences', models.TextField(blank=True)),
                ('projects', models.TextField(blank=True)),
                ('portfolio_links', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='profiles', to='api.skilltag')),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('application_link', models.URLField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('role_type', models.CharField(choices=[('SWE', 'Software Engineering'), ('DS', 'Data Science'), ('PM', 'Product Management'), ('UIUX', 'UI/UX Design'), ('DE', 'Data Engineering'), ('ML', 'Machine Learning'), ('FS', 'Full Stack'), ('IT', 'Information Technology'), ('BA', 'Business Analysis'), ('OT', 'Other')], default='OT', max_length=8)),
                ('required_skills', models.ManyToManyField(blank=True, related_name='jobs', to='api.skilltag')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('offer', 'Offer'), ('rejection', 'Rejection'), ('pending', 'Pending')], max_length=12)),
                ('channel', models.CharField(blank=True, choices=[('portal', 'Company Portal'), ('linkedin', 'LinkedIn'), ('careerfair', 'Career Fair'), ('referral', 'Referral'), ('email', 'Direct Email'), ('other', 'Other')], max_length=12)),
                ('interview_format', models.CharField(blank=True, choices=[('online', 'Online'), ('inperson', 'In-Person'), ('both', 'Both'), ('none', 'No Interview')], max_length=12)),
                ('timeline', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='api.joblisting')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
